// ==================== MAIN ENTRY POINTS ====================

function doGet() {
  return HtmlService.createTemplateFromFile('Login')
    .evaluate()
    .setTitle('Training Management System')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

function include(filename) {
  return HtmlService.createHtmlOutputFromFile(filename).getContent();
}

// ==================== SPREADSHEET CONFIGURATION ====================

const SPREADSHEET_ID = '1uUNDhLPDNAbXneTC8tBlRxaAmhoFaQ1oWH8XmQzitGc';
const LOGIN_SHEET_NAME = 'Login and registeration';

// Settings sheet (for Training Categories + Applications)
const SETTINGS_SHEET_NAME = 'TMS_Settings';
const DEFAULT_TRAINING_CATEGORIES = ['SBL', 'ILT', 'ISMS', 'Misc'];
const DEFAULT_APPLICATIONS = [
  'Zip Core, Schedule and Forecast',
  'Zip Clock',
  'Zip Ordering and Inventory',
  'Plum POS',
  'Zip Checklist/HACCP'
];

// Quiz Module Configuration
const QUIZ_SHEET_NAME = 'Quiz';
const ASSIGNED_QUIZ_SHEET_NAME = 'Quiz_Assignments';
const QUIZ_RESULTS_SHEET_NAME = 'Quiz_Results';

function getSpreadsheet() {
  return SpreadsheetApp.openById(SPREADSHEET_ID);
}

// ==================== SHEET INITIALIZATION ====================

function initializeSheets() {
  const ss = getSpreadsheet();

  // Define all required sheets with their headers
  const sheetsConfig = {
    'ILT': ['Batch', 'Category', 'Application', 'Trainee Name', 'Trainee Email', 'Level', 'Start Date', 'End Date', 'Duration (Days)'],
    'Holidays': ['Date'],
    'ILT_Trainings': ['Training ID', 'Name', 'Description', 'Category', 'Start Date', 'End Date', 'Trainer', 'Location', 'Max Participants', 'Status', 'Created Date'],
    'ILT_Enrollments': ['Enrollment ID', 'Training ID', 'Trainee Email', 'Trainee Name', 'Enrollment Date', 'Status', 'Progress', 'Completion Date'],
    'ILT_Evaluations': ['Evaluation ID', 'Training ID', 'Trainee Email', 'Evaluator', 'Date', 'Score', 'Comments', 'Status'],
    'ILT_Certifications': ['Certification ID', 'Training ID', 'Trainee Email', 'Trainee Name', 'Issue Date', 'Expiry Date', 'Status'],
    'SBL_Videos': ['Video ID', 'Title', 'Description', 'Category', 'Duration', 'URL', 'Thumbnail', 'Upload Date', 'Views', 'Status'],
    'SBL_Progress': ['Progress ID', 'Video ID', 'Trainee Email', 'Watch Time', 'Completed', 'Last Watched', 'Score'],
    'SBL_Evaluations': ['Evaluation ID', 'Video ID', 'Trainee Email', 'Date', 'Score', 'Status'],
    'SBL_Certifications': ['Certification ID', 'Video ID', 'Trainee Email', 'Trainee Name', 'Completion Date', 'Status'],
    'Compliance_Events': ['Event ID', 'Name', 'Type', 'Description', 'Due Date', 'Status', 'Created Date'],
    'Compliance_Status': ['Status ID', 'Trainee Email', 'Trainee Name', 'Event ID', 'Compliance %', 'Status', 'Last Updated'],
    'Compliance_Reports': ['Report ID', 'Name', 'Type', 'Generated Date', 'Generated By', 'Status'],
    'Compliance_Requirements': ['Requirement ID', 'Name', 'Description', 'Category', 'Due Date', 'Status'],

    // NEW: Settings sheet for dynamic dropdowns
    'TMS_Settings': ['Training Categories', '', 'Applications'],

    // Quiz Assignment and Results sheets
    'Quiz_Assignments': ['Assignment ID', 'Batch', 'Trainee Email', 'Trainee Name', 'Application', 'Test Number', 'Assigned By', 'Assigned Date', 'Status', 'Due Date'],
    'Quiz_Results': ['Result ID', 'Assignment ID', 'Batch', 'Trainee Email', 'Trainee Name', 'Application', 'Test Number', 'Total Questions', 'Correct Answers', 'Score Percentage', 'Submitted Date', 'Time Taken (mins)', 'Answers JSON']
  };

  for (const [sheetName, headers] of Object.entries(sheetsConfig)) {
    let sheet = ss.getSheetByName(sheetName);
    if (!sheet) {
      sheet = ss.insertSheet(sheetName);
      sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
      sheet.getRange(1, 1, 1, headers.length).setFontWeight('bold');
      sheet.setFrozenRows(1);
    }
  }

  // Seed defaults into settings sheet (if empty)
  ensureSettingsSheet_();

  return { success: true, message: 'All sheets initialized successfully' };
}

// ==================== SETTINGS (CATEGORIES & APPLICATIONS) ====================

function ensureSettingsSheet_() {
  const ss = getSpreadsheet();
  let sheet = ss.getSheetByName(SETTINGS_SHEET_NAME);

  if (!sheet) {
    sheet = ss.insertSheet(SETTINGS_SHEET_NAME);
    // Column A = Categories, Column C = Applications (Column B blank)
    sheet.getRange(1, 1, 1, 3).setValues([['Training Categories', '', 'Applications']]);
    sheet.getRange(1, 1, 1, 3).setFontWeight('bold');
    sheet.setFrozenRows(1);
  }

  const lastRow = sheet.getLastRow();
  const catValues = lastRow >= 2 ? sheet.getRange(2, 1, lastRow - 1, 1).getValues().flat().filter(Boolean) : [];
  const appValues = lastRow >= 2 ? sheet.getRange(2, 3, lastRow - 1, 1).getValues().flat().filter(Boolean) : [];

  if (catValues.length === 0) {
    sheet.getRange(2, 1, DEFAULT_TRAINING_CATEGORIES.length, 1)
      .setValues(DEFAULT_TRAINING_CATEGORIES.map(x => [x]));
  }
  if (appValues.length === 0) {
    sheet.getRange(2, 3, DEFAULT_APPLICATIONS.length, 1)
      .setValues(DEFAULT_APPLICATIONS.map(x => [x]));
  }

  return sheet;
}

function getUserTypeByEmail_(email) {
  const ss = getSpreadsheet();
  const sheet = ss.getSheetByName(LOGIN_SHEET_NAME);
  if (!sheet || sheet.getLastRow() < 2) return '';

  const data = sheet.getDataRange().getValues();
  const target = String(email || '').trim().toLowerCase();

  for (let i = 1; i < data.length; i++) {
    const rowEmail = String(data[i][1]).trim().toLowerCase(); // Column B
    const rowType = String(data[i][6]).trim();               // Column G
    if (rowEmail && rowEmail === target) return rowType;
  }
  return '';
}

function assertTrainer_(userEmail) {
  const type = (getUserTypeByEmail_(userEmail) || '').toLowerCase().trim();
  if (type !== 'trainer') throw new Error('Access denied: Only Trainers can use Settings.');
}

/**
 * Used by UI to populate dropdowns dynamically
 */
function getDropdownOptions() {
  const sheet = ensureSettingsSheet_();
  const lastRow = sheet.getLastRow();

  const cats = lastRow >= 2 ? sheet.getRange(2, 1, lastRow - 1, 1).getValues().flat() : [];
  const apps = lastRow >= 2 ? sheet.getRange(2, 3, lastRow - 1, 1).getValues().flat() : [];

  const categories = cats.map(v => String(v || '').trim()).filter(Boolean);
  const applications = apps.map(v => String(v || '').trim()).filter(Boolean);

  const uniqKeepCase = (arr) => {
    const seen = new Set();
    const out = [];
    arr.forEach(x => {
      const k = x.toLowerCase();
      if (!seen.has(k)) {
        seen.add(k);
        out.push(x);
      }
    });
    return out;
  };

  return {
    categories: uniqKeepCase(categories).sort((a, b) => a.localeCompare(b)),
    applications: uniqKeepCase(applications).sort((a, b) => a.localeCompare(b))
  };
}

/**
 * Settings action: add a new Training Category (trainer only)
 */
function addTrainingCategoryOption(category, userEmail) {
  assertTrainer_(userEmail);

  const value = String(category || '').trim();
  if (!value) return { success: false, message: 'Category cannot be empty.' };

  const opts = getDropdownOptions();
  if (opts.categories.some(c => c.toLowerCase() === value.toLowerCase())) {
    return { success: false, message: 'Category already exists.' };
  }

  const sheet = ensureSettingsSheet_();
  const lastRow = Math.max(sheet.getLastRow(), 1);
  sheet.getRange(lastRow + 1, 1).setValue(value);

  // Create a new sheet for this category with same headers as ILT
  createCategorySheet_(value);

  return { success: true, message: 'Training category added successfully.' };
}

/**
 * Creates a new sheet for a category with the same headers as ILT
 */
function createCategorySheet_(categoryName) {
  const ss = getSpreadsheet();
  const sheetName = categoryName;

  // Check if sheet already exists
  let sheet = ss.getSheetByName(sheetName);
  if (sheet) {
    return sheet; // Sheet already exists
  }

  // Create new sheet with ILT headers
  const iltHeaders = ['Batch', 'Category', 'Application', 'Trainee Name', 'Trainee Email', 'Level', 'Start Date', 'End Date', 'Duration (Days)'];
  sheet = ss.insertSheet(sheetName);
  sheet.getRange(1, 1, 1, iltHeaders.length).setValues([iltHeaders]);
  sheet.getRange(1, 1, 1, iltHeaders.length).setFontWeight('bold');
  sheet.setFrozenRows(1);

  return sheet;
}

/**
 * Settings action: add a new Application (trainer only)
 */
function addApplicationOption(application, userEmail) {
  assertTrainer_(userEmail);

  const value = String(application || '').trim();
  if (!value) return { success: false, message: 'Application cannot be empty.' };

  const opts = getDropdownOptions();
  if (opts.applications.some(a => a.toLowerCase() === value.toLowerCase())) {
    return { success: false, message: 'Application already exists.' };
  }

  const sheet = ensureSettingsSheet_();
  const lastRow = Math.max(sheet.getLastRow(), 1);
  sheet.getRange(lastRow + 1, 3).setValue(value);

  return { success: true, message: 'Application added successfully.' };
}

/**
 * Settings action: delete a Training Category (trainer only)
 */
function deleteTrainingCategoryOption(category, userEmail) {
  assertTrainer_(userEmail);

  const value = String(category || '').trim();
  if (!value) return { success: false, message: 'Category cannot be empty.' };

  const sheet = ensureSettingsSheet_();
  const lastRow = sheet.getLastRow();

  if (lastRow < 2) {
    return { success: false, message: 'No categories to delete.' };
  }

  const catValues = sheet.getRange(2, 1, lastRow - 1, 1).getValues();
  let rowToDelete = -1;

  for (let i = 0; i < catValues.length; i++) {
    if (String(catValues[i][0]).trim().toLowerCase() === value.toLowerCase()) {
      rowToDelete = i + 2; // +2 because we start from row 2
      break;
    }
  }

  if (rowToDelete === -1) {
    return { success: false, message: 'Category not found.' };
  }

  // Clear the cell instead of deleting the row to preserve application column alignment
  sheet.getRange(rowToDelete, 1).clearContent();

  // Compact the column by removing empty cells
  compactSettingsColumn_(sheet, 1);

  return { success: true, message: 'Training category deleted successfully.' };
}

/**
 * Settings action: delete an Application (trainer only)
 */
function deleteApplicationOption(application, userEmail) {
  assertTrainer_(userEmail);

  const value = String(application || '').trim();
  if (!value) return { success: false, message: 'Application cannot be empty.' };

  const sheet = ensureSettingsSheet_();
  const lastRow = sheet.getLastRow();

  if (lastRow < 2) {
    return { success: false, message: 'No applications to delete.' };
  }

  const appValues = sheet.getRange(2, 3, lastRow - 1, 1).getValues();
  let rowToDelete = -1;

  for (let i = 0; i < appValues.length; i++) {
    if (String(appValues[i][0]).trim().toLowerCase() === value.toLowerCase()) {
      rowToDelete = i + 2;
      break;
    }
  }

  if (rowToDelete === -1) {
    return { success: false, message: 'Application not found.' };
  }

  sheet.getRange(rowToDelete, 3).clearContent();
  compactSettingsColumn_(sheet, 3);

  return { success: true, message: 'Application deleted successfully.' };
}

/**
 * Helper to compact a column by moving non-empty cells up
 */
function compactSettingsColumn_(sheet, col) {
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return;

  const values = sheet.getRange(2, col, lastRow - 1, 1).getValues();
  const nonEmpty = values.filter(row => String(row[0]).trim() !== '');

  // Clear the column from row 2 onwards
  sheet.getRange(2, col, lastRow - 1, 1).clearContent();

  // Write back non-empty values
  if (nonEmpty.length > 0) {
    sheet.getRange(2, col, nonEmpty.length, 1).setValues(nonEmpty);
  }
}

// ==================== AUTHENTICATION ====================

function authenticateUser(email, password) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName(LOGIN_SHEET_NAME);

    if (!sheet) {
      return { success: false, message: 'Login sheet not found' };
    }

    const data = sheet.getDataRange().getValues();

    for (let i = 1; i < data.length; i++) {
      const rowEmail = String(data[i][1]).trim().toLowerCase(); // Column B
      const rowPassword = String(data[i][5]).trim(); // Column F
      const rowType = String(data[i][6]).trim(); // Column G
      const rowName = String(data[i][0]).trim(); // Column A

      if (rowEmail === String(email || '').toLowerCase() && rowPassword === String(password || '')) {
        return {
          success: true,
          user: {
            email: rowEmail,
            name: rowName || rowEmail.split('@')[0],
            type: rowType || 'Trainee'
          }
        };
      }
    }

    return { success: false, message: 'Invalid email or password' };
  } catch (error) {
    return { success: false, message: error.message };
  }
}

function sendPasswordRecovery(email) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName(LOGIN_SHEET_NAME);

    if (!sheet) {
      return { success: false, message: 'Login sheet not found' };
    }

    const data = sheet.getDataRange().getValues();

    for (let i = 1; i < data.length; i++) {
      const rowEmail = String(data[i][1]).trim().toLowerCase();
      const rowPassword = String(data[i][5]).trim(); // Column F

      if (rowEmail === String(email || '').toLowerCase()) {
        MailApp.sendEmail({
          to: email,
          subject: 'TMS Password Recovery',
          body: `Hello,\n\nYour password for the Training Management System is: ${rowPassword}\n\nPlease keep this information secure.\n\nBest regards,\nTMS Team`
        });

        return { success: true, message: 'Password sent to your email' };
      }
    }

    return { success: false, message: 'Email not found in our records' };
  } catch (error) {
    return { success: false, message: error.message };
  }
}

function getUserPermissions(userType) {
  const type = (userType || '').toLowerCase().trim();

  if (type === 'trainer') {
    return {
      ilt: { dashboard: true, progress: true, evaluations: true, reports: true },
      sbl: { dashboard: true, videos: true, evaluations: true, reports: true },
      compliance: { calendar: true, status: true, reports: true, management: true }
    };
  }

  // Default trainee permissions
  return {
    ilt: { dashboard: false, progress: true, evaluations: true, reports: false },
    sbl: { dashboard: false, videos: true, evaluations: true, reports: false },
    compliance: { calendar: true, status: true, reports: true, management: false }
  };
}

// ==================== HOLIDAYS ====================

function getHolidays() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('Holidays');

    if (!sheet || sheet.getLastRow() < 2) {
      return [];
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 1).getValues();
    return data.map(row => {
      if (row[0] instanceof Date) {
        return Utilities.formatDate(row[0], Session.getScriptTimeZone(), 'yyyy-MM-dd');
      }
      return String(row[0]);
    }).filter(Boolean);
  } catch (error) {
    console.error('Error getting holidays:', error);
    return [];
  }
}

// ==================== TRAINING DATA ====================

function getNextBatchNumber(category) {
  try {
    // Guard against missing category parameter
    category = category || 'ILT';

    const ss = getSpreadsheet();

    // Determine which sheet to check based on category
    const defaultCategories = ['ilt', 'sbl', 'isms', 'misc'];
    const isDefaultCategory = defaultCategories.includes(category.toLowerCase());
    const sheetName = isDefaultCategory ? 'ILT' : category;

    const sheet = ss.getSheetByName(sheetName);

    if (!sheet || sheet.getLastRow() < 2) {
      return 1;
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 1).getValues();
    let maxBatch = 0;

    data.forEach(row => {
      const batchNum = parseInt(String(row[0]).replace(/\D/g, ''), 10);
      if (!isNaN(batchNum) && batchNum > maxBatch) {
        maxBatch = batchNum;
      }
    });

    return maxBatch + 1;
  } catch (error) {
    console.error('Error getting next batch number:', error);
    return 1;
  }
}

function saveTrainingData(trainingData) {
  try {
    const ss = getSpreadsheet();

    // Determine which sheet to use based on category
    const defaultCategories = ['ilt', 'sbl', 'isms', 'misc'];
    const isDefaultCategory = defaultCategories.includes(trainingData.category.toLowerCase());
    const sheetName = isDefaultCategory ? 'ILT' : trainingData.category;

    let sheet = ss.getSheetByName(sheetName);

    // If custom category sheet doesn't exist, create it
    if (!sheet) {
      sheet = createCategorySheet_(sheetName);
    }

    if (!sheet) {
      return { success: false, message: 'Sheet not found and could not be created' };
    }

    const rowsToAdd = [];

    trainingData.applications.forEach(app => {
      trainingData.levels.forEach(level => {
        trainingData.traineeEmails.forEach((email, i) => {
          const duration = calculateWorkingDays(trainingData.startDate, trainingData.endDate);
          rowsToAdd.push([
            trainingData.batchCount,
            trainingData.category,
            app,
            trainingData.traineeNames[i],
            email,
            level,
            trainingData.startDate,
            trainingData.endDate,
            duration
          ]);
        });
      });
    });

    if (rowsToAdd.length > 0) {
      const lastRow = sheet.getLastRow();
      sheet.getRange(lastRow + 1, 1, rowsToAdd.length, 9).setValues(rowsToAdd);
    }

    return { success: true, message: 'Training data saved successfully' };
  } catch (error) {
    console.error('Error saving training data:', error);
    return { success: false, message: error.message };
  }
}

function calculateWorkingDays(startDate, endDate) {
  try {
    const start = new Date(startDate);
    const end = new Date(endDate);
    const holidays = getHolidays();

    let count = 0;
    const current = new Date(start);

    while (current <= end) {
      const day = current.getDay();
      const dateStr = Utilities.formatDate(current, Session.getScriptTimeZone(), 'yyyy-MM-dd');

      if (day !== 0 && day !== 6 && !holidays.includes(dateStr)) {
        count++;
      }

      current.setDate(current.getDate() + 1);
    }

    return count;
  } catch (error) {
    console.error('Error calculating working days:', error);
    return 0;
  }
}

// ==================== ILT DATA FUNCTIONS ====================

function getILTDashboardData() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('ILT');

    if (!sheet || sheet.getLastRow() < 2) {
      return { totalTrainings: 0, totalTrainees: 0, upcomingTrainings: 0, recentTrainings: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 9).getValues();
    const today = new Date();

    const uniqueTrainings = new Set();
    const uniqueTrainees = new Set();
    let upcomingCount = 0;
    const recentTrainings = [];

    data.forEach(row => {
      if (row[0]) {
        uniqueTrainings.add(row[0] + '|' + row[2]);
        uniqueTrainees.add(row[4]);

        const startDate = new Date(row[6]);
        if (startDate > today) upcomingCount++;
      }
    });

    const seenTrainings = new Set();
    for (let i = data.length - 1; i >= 0 && recentTrainings.length < 10; i--) {
      const key = data[i][0] + '|' + data[i][2];
      if (data[i][0] && !seenTrainings.has(key)) {
        seenTrainings.add(key);
        const startDate = new Date(data[i][6]);
        const status = startDate > today ? 'Scheduled' : (new Date(data[i][7]) < today ? 'Completed' : 'In Progress');

        recentTrainings.push({
          name: data[i][2],
          category: data[i][1],
          startDate: Utilities.formatDate(new Date(data[i][6]), Session.getScriptTimeZone(), 'yyyy-MM-dd'),
          endDate: Utilities.formatDate(new Date(data[i][7]), Session.getScriptTimeZone(), 'yyyy-MM-dd'),
          status: status
        });
      }
    }

    return {
      totalTrainings: uniqueTrainings.size,
      totalTrainees: uniqueTrainees.size,
      upcomingTrainings: upcomingCount,
      recentTrainings: recentTrainings
    };
  } catch (error) {
    console.error('Error getting ILT dashboard data:', error);
    return { totalTrainings: 0, totalTrainees: 0, upcomingTrainings: 0, recentTrainings: [] };
  }
}

function getILTProgressData(userEmail) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('ILT');

    if (!sheet || sheet.getLastRow() < 2) {
      return { trainings: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 9).getValues();
    const trainings = [];
    const today = new Date();

    data.forEach(row => {
      if (row[4] && String(row[4]).toLowerCase() === String(userEmail).toLowerCase()) {
        const startDate = new Date(row[6]);
        const endDate = new Date(row[7]);

        let progress = 0;
        let status = 'Scheduled';

        if (today >= startDate && today <= endDate) {
          const totalDays = (endDate - startDate) / (1000 * 60 * 60 * 24);
          const elapsedDays = (today - startDate) / (1000 * 60 * 60 * 24);
          progress = Math.min(Math.round((elapsedDays / totalDays) * 100), 100);
          status = 'In Progress';
        } else if (today > endDate) {
          progress = 100;
          status = 'Completed';
        }

        trainings.push({
          name: row[2],
          level: row[5],
          progress: progress,
          status: status
        });
      }
    });

    return { trainings: trainings };
  } catch (error) {
    console.error('Error getting ILT progress data:', error);
    return { trainings: [] };
  }
}

function getILTEvaluationsData(userEmail) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('ILT_Evaluations');

    if (!sheet || sheet.getLastRow() < 2) {
      return { evaluations: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 8).getValues();
    const evaluations = [];

    data.forEach(row => {
      if (!userEmail || String(row[2]).toLowerCase() === String(userEmail).toLowerCase()) {
        evaluations.push({
          training: row[1],
          date: row[4] ? Utilities.formatDate(new Date(row[4]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
          score: row[5] || '-',
          evaluator: row[3] || '-',
          status: row[7] || 'Pending'
        });
      }
    });

    return { evaluations: evaluations };
  } catch (error) {
    console.error('Error getting ILT evaluations data:', error);
    return { evaluations: [] };
  }
}

function getILTReportsData() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('ILT_Certifications');

    if (!sheet || sheet.getLastRow() < 2) {
      return { certifications: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 7).getValues();
    const certifications = [];

    data.forEach(row => {
      certifications.push({
        trainee: row[3] || '-',
        training: row[1] || '-',
        certDate: row[4] ? Utilities.formatDate(new Date(row[4]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
        expiryDate: row[5] ? Utilities.formatDate(new Date(row[5]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
        status: row[6] || 'Active'
      });
    });

    return { certifications: certifications };
  } catch (error) {
    console.error('Error getting ILT reports data:', error);
    return { certifications: [] };
  }
}

// ==================== SBL DATA FUNCTIONS ====================

function getSBLDashboardData() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('SBL_Videos');

    if (!sheet || sheet.getLastRow() < 2) {
      return { totalVideos: 0, totalViews: 0, completedVideos: 0 };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 10).getValues();
    let totalViews = 0;

    data.forEach(row => {
      totalViews += Number(row[8]) || 0;
    });

    return {
      totalVideos: data.length,
      totalViews: totalViews,
      completedVideos: 0
    };
  } catch (error) {
    console.error('Error getting SBL dashboard data:', error);
    return { totalVideos: 0, totalViews: 0, completedVideos: 0 };
  }
}

function getSBLVideosData() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('SBL_Videos');

    if (!sheet || sheet.getLastRow() < 2) {
      return { videos: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 10).getValues();
    const videos = [];

    data.forEach(row => {
      videos.push({
        title: row[1] || 'Untitled',
        description: row[2] || '',
        duration: row[4] || '0:00',
        views: row[8] || 0
      });
    });

    return { videos: videos };
  } catch (error) {
    console.error('Error getting SBL videos data:', error);
    return { videos: [] };
  }
}

function getSBLEvaluationsData(userEmail) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('SBL_Evaluations');

    if (!sheet || sheet.getLastRow() < 2) {
      return { evaluations: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 6).getValues();
    const evaluations = [];

    data.forEach(row => {
      if (!userEmail || String(row[2]).toLowerCase() === String(userEmail).toLowerCase()) {
        evaluations.push({
          video: row[1] || '-',
          date: row[3] ? Utilities.formatDate(new Date(row[3]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
          score: row[4] || '-',
          status: row[5] || 'Pending'
        });
      }
    });

    return { evaluations: evaluations };
  } catch (error) {
    console.error('Error getting SBL evaluations data:', error);
    return { evaluations: [] };
  }
}

function getSBLReportsData() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('SBL_Certifications');

    if (!sheet || sheet.getLastRow() < 2) {
      return { certifications: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 6).getValues();
    const certifications = [];

    data.forEach(row => {
      certifications.push({
        trainee: row[3] || '-',
        video: row[1] || '-',
        completionDate: row[4] ? Utilities.formatDate(new Date(row[4]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
        status: row[5] || 'Active'
      });
    });

    return { certifications: certifications };
  } catch (error) {
    console.error('Error getting SBL reports data:', error);
    return { certifications: [] };
  }
}

// ==================== COMPLIANCE DATA FUNCTIONS ====================

function getComplianceCalendarData() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('Compliance_Events');

    if (!sheet || sheet.getLastRow() < 2) {
      return { events: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 7).getValues();
    const events = [];

    data.forEach(row => {
      events.push({
        name: row[1] || '-',
        type: row[2] || '-',
        dueDate: row[4] ? Utilities.formatDate(new Date(row[4]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
        status: row[5] || 'Pending'
      });
    });

    return { events: events };
  } catch (error) {
    console.error('Error getting compliance calendar data:', error);
    return { events: [] };
  }
}

function getComplianceStatusData(userEmail) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('Compliance_Status');

    if (!sheet || sheet.getLastRow() < 2) {
      return { status: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 7).getValues();
    const status = [];

    data.forEach(row => {
      if (!userEmail || String(row[1]).toLowerCase() === String(userEmail).toLowerCase()) {
        status.push({
          trainee: row[2] || '-',
          event: row[3] || '-',
          compliance: row[4] || 0,
          status: row[5] || 'Pending'
        });
      }
    });

    return { status: status };
  } catch (error) {
    console.error('Error getting compliance status data:', error);
    return { status: [] };
  }
}

function getComplianceReportsData() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('Compliance_Reports');

    if (!sheet || sheet.getLastRow() < 2) {
      return { reports: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 6).getValues();
    const reports = [];

    data.forEach(row => {
      reports.push({
        name: row[1] || '-',
        type: row[2] || '-',
        generatedDate: row[3] ? Utilities.formatDate(new Date(row[3]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
        generatedBy: row[4] || '-',
        status: row[5] || 'Active'
      });
    });

    return { reports: reports };
  } catch (error) {
    console.error('Error getting compliance reports data:', error);
    return { reports: [] };
  }
}

// ==================== CALENDAR FUNCTIONS ====================

function getCalendarEvents(userEmail, userType) {
  try {
    const ss = getSpreadsheet();
    const iltSheet = ss.getSheetByName('ILT');

    if (!iltSheet || iltSheet.getLastRow() < 2) {
      return [];
    }

    const data = iltSheet.getRange(2, 1, iltSheet.getLastRow() - 1, 9).getValues();
    const eventsMap = {};
    const isTrainee = (userType || '').toLowerCase() === 'trainee';

    data.forEach(row => {
      if (!row[0]) return;

      const traineeEmail = String(row[4]).toLowerCase().trim();

      // For trainees, only show their own trainings
      if (isTrainee && traineeEmail !== String(userEmail).toLowerCase()) {
        return;
      }

      const key = `${row[0]}|${row[2]}|${row[6]}|${row[7]}`;

      if (!eventsMap[key]) {
        let startDate = row[6];
        let endDate = row[7];

        if (startDate instanceof Date) {
          startDate = Utilities.formatDate(startDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');
        }
        if (endDate instanceof Date) {
          endDate = Utilities.formatDate(endDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');
        }

        eventsMap[key] = {
          batch: row[0],
          category: row[1],
          application: row[2],
          startDate: startDate,
          endDate: endDate,
          duration: row[8],
          trainees: []
        };
      }

      eventsMap[key].trainees.push({
        name: row[3],
        email: row[4],
        level: row[5]
      });
    });

    return Object.values(eventsMap);
  } catch (error) {
    console.error('Error getting calendar events:', error);
    return [];
  }
}

// ==================== SYLLABUS FUNCTIONS ====================

function getSyllabusForApplication(application) {
  const syllabusMap = {
    'Zip Core, Schedule and Forecast': [
      { day: 'Day 1', topic: 'Introduction to Zip Core' },
      { day: 'Day 1', topic: 'Navigation and Dashboard Overview' },
      { day: 'Day 2', topic: 'Schedule Creation Basics' },
      { day: 'Day 2', topic: 'Employee Management' },
      { day: 'Day 3', topic: 'Forecasting Fundamentals' },
      { day: 'Day 3', topic: 'Labor Cost Analysis' },
      { day: 'Day 4', topic: 'Advanced Scheduling Features' },
      { day: 'Day 4', topic: 'Reports and Analytics' }
    ],
    'Zip Clock': [
      { day: 'Day 1', topic: 'Zip Clock Overview' },
      { day: 'Day 1', topic: 'Time Clock Setup' },
      { day: 'Day 2', topic: 'Employee Clock In/Out' },
      { day: 'Day 2', topic: 'Break Management' },
      { day: 'Day 3', topic: 'Timesheet Review' },
      { day: 'Day 3', topic: 'Overtime Tracking' },
      { day: 'Day 4', topic: 'Payroll Integration' },
      { day: 'Day 4', topic: 'Reports and Compliance' }
    ],
    'Zip Ordering and Inventory': [
      { day: 'Day 1', topic: 'Inventory Management Basics' },
      { day: 'Day 1', topic: 'Item Setup and Configuration' },
      { day: 'Day 2', topic: 'Order Creation' },
      { day: 'Day 2', topic: 'Vendor Management' },
      { day: 'Day 3', topic: 'Receiving and Stock Updates' },
      { day: 'Day 3', topic: 'Waste Tracking' },
      { day: 'Day 4', topic: 'Inventory Counts' },
      { day: 'Day 4', topic: 'Cost Analysis and Reports' }
    ],
    'Plum POS': [
      { day: 'Day 1', topic: 'POS System Overview' },
      { day: 'Day 1', topic: 'Menu Configuration' },
      { day: 'Day 2', topic: 'Order Taking Process' },
      { day: 'Day 2', topic: 'Payment Processing' },
      { day: 'Day 3', topic: 'Table Management' },
      { day: 'Day 3', topic: 'Modifiers and Special Requests' },
      { day: 'Day 4', topic: 'End of Day Procedures' },
      { day: 'Day 4', topic: 'Reporting and Analytics' }
    ],
    'Zip Checklist/HACCP': [
      { day: 'Day 1', topic: 'HACCP Principles Overview' },
      { day: 'Day 1', topic: 'Checklist Setup' },
      { day: 'Day 2', topic: 'Temperature Logging' },
      { day: 'Day 2', topic: 'Food Safety Compliance' },
      { day: 'Day 3', topic: 'Corrective Actions' },
      { day: 'Day 3', topic: 'Audit Preparation' },
      { day: 'Day 4', topic: 'Reports and Documentation' },
      { day: 'Day 4', topic: 'Best Practices Review' }
    ]
  };

  const appKey = Object.keys(syllabusMap).find(key =>
    application.toLowerCase().includes(key.toLowerCase().split(',')[0].trim())
  );

  return syllabusMap[appKey] || [
    { day: 'Day 1', topic: 'Introduction' },
    { day: 'Day 2', topic: 'Core Features' },
    { day: 'Day 3', topic: 'Advanced Topics' },
    { day: 'Day 4', topic: 'Review and Assessment' }
  ];
}

// ==================== TRAINING PROGRESS FUNCTIONS ====================

function initializeProgressSheet() {
  const ss = getSpreadsheet();
  let sheet = ss.getSheetByName('Training_Progress');

  if (!sheet) {
    sheet = ss.insertSheet('Training_Progress');
    const headers = ['Trainee Email', 'Trainee Name', 'Batch', 'Application', 'Day', 'Topic', 'Status', 'Marked By', 'Marked Date', 'Start Date', 'End Date'];
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
    sheet.getRange(1, 1, 1, headers.length).setFontWeight('bold');
    sheet.setFrozenRows(1);
  }

  return sheet;
}

function createProgressEntries(trainingData) {
  try {
    const progressSheet = initializeProgressSheet();
    const rowsToAdd = [];

    trainingData.applications.forEach(app => {
      const syllabus = getSyllabusForApplication(app);

      trainingData.traineeEmails.forEach((email, i) => {
        syllabus.forEach(topic => {
          rowsToAdd.push([
            email,
            trainingData.traineeNames[i],
            trainingData.batchCount,
            app,
            topic.day,
            topic.topic,
            'Not Done',
            '',
            '',
            trainingData.startDate,
            trainingData.endDate
          ]);
        });
      });
    });

    if (rowsToAdd.length > 0) {
      const lastRow = progressSheet.getLastRow();
      progressSheet.getRange(lastRow + 1, 1, rowsToAdd.length, 11).setValues(rowsToAdd);
    }

    return { success: true, entriesCreated: rowsToAdd.length };
  } catch (error) {
    console.error('Error creating progress entries:', error);
    return { success: false, message: error.message };
  }
}

function getTrainingsForTrainer(filters) {
  try {
    const ss = getSpreadsheet();
    const iltSheet = ss.getSheetByName('ILT');

    if (!iltSheet || iltSheet.getLastRow() < 2) {
      return { trainings: [] };
    }

    const data = iltSheet.getRange(2, 1, iltSheet.getLastRow() - 1, 9).getValues();
    const trainingsMap = {};

    data.forEach(row => {
      if (!row[0]) return;

      const traineeEmail = String(row[4]).toLowerCase().trim();
      const traineeName = String(row[3]).trim();
      const application = String(row[2]).trim();
      const batch = String(row[0]).trim();
      let startDate = row[6];
      let endDate = row[7];

      if (filters) {
        if (filters.traineeName && !traineeName.toLowerCase().includes(filters.traineeName.toLowerCase())) return;
        if (filters.application && application !== filters.application) return;
        if (filters.startDate) {
          const filterStart = new Date(filters.startDate);
          const rowStart = new Date(startDate);
          if (rowStart < filterStart) return;
        }
        if (filters.endDate) {
          const filterEnd = new Date(filters.endDate);
          const rowEnd = new Date(endDate);
          if (rowEnd > filterEnd) return;
        }
      }

      if (startDate instanceof Date) startDate = Utilities.formatDate(startDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');
      if (endDate instanceof Date) endDate = Utilities.formatDate(endDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');

      const key = `${batch}|${application}|${traineeEmail}`;

      if (!trainingsMap[key]) {
        trainingsMap[key] = {
          batch: batch,
          application: application,
          traineeEmail: traineeEmail,
          traineeName: traineeName,
          startDate: startDate,
          endDate: endDate,
          level: row[5]
        };
      }
    });

    return { trainings: Object.values(trainingsMap) };
  } catch (error) {
    console.error('Error getting trainings for trainer:', error);
    return { trainings: [] };
  }
}

function getTraineeProgress(traineeEmail, application, batch) {
  try {
    const ss = getSpreadsheet();
    const progressSheet = ss.getSheetByName('Training_Progress');

    if (!progressSheet || progressSheet.getLastRow() < 2) {
      const syllabus = getSyllabusForApplication(application);
      return {
        progress: syllabus.map(topic => ({
          day: topic.day,
          topic: topic.topic,
          status: 'Not Done',
          markedBy: '',
          markedDate: ''
        })),
        fromSyllabus: true
      };
    }

    const data = progressSheet.getRange(2, 1, progressSheet.getLastRow() - 1, 11).getValues();
    const progress = [];

    data.forEach((row, index) => {
      const rowEmail = String(row[0]).toLowerCase().trim();
      const rowApp = String(row[3]).trim();
      const rowBatch = String(row[2]).trim();

      if (rowEmail === String(traineeEmail).toLowerCase() &&
        rowApp.toLowerCase().includes(String(application).toLowerCase().split(',')[0].trim()) &&
        (!batch || rowBatch === batch)) {
        progress.push({
          rowIndex: index + 2,
          day: row[4],
          topic: row[5],
          status: row[6] || 'Not Done',
          markedBy: row[7] || '',
          markedDate: row[8] ? Utilities.formatDate(new Date(row[8]), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm') : ''
        });
      }
    });

    if (progress.length === 0) {
      const syllabus = getSyllabusForApplication(application);
      return {
        progress: syllabus.map(topic => ({
          day: topic.day,
          topic: topic.topic,
          status: 'Not Done',
          markedBy: '',
          markedDate: ''
        })),
        fromSyllabus: true
      };
    }

    return { progress: progress, fromSyllabus: false };
  } catch (error) {
    console.error('Error getting trainee progress:', error);
    return { progress: [], error: error.message };
  }
}

function markTopicStatus(traineeEmail, application, batch, day, topic, status, trainerEmail) {
  try {
    const ss = getSpreadsheet();
    let progressSheet = ss.getSheetByName('Training_Progress');

    if (!progressSheet) {
      progressSheet = initializeProgressSheet();
    }

    const data = progressSheet.getRange(2, 1, Math.max(progressSheet.getLastRow() - 1, 1), 11).getValues();
    let rowFound = false;

    for (let i = 0; i < data.length; i++) {
      const rowEmail = String(data[i][0]).toLowerCase().trim();
      const rowApp = String(data[i][3]).trim();
      const rowBatch = String(data[i][2]).trim();
      const rowDay = String(data[i][4]).trim();
      const rowTopic = String(data[i][5]).trim();

      if (rowEmail === String(traineeEmail).toLowerCase() &&
        rowApp.toLowerCase().includes(String(application).toLowerCase().split(',')[0].trim()) &&
        rowBatch === batch &&
        rowDay === day &&
        rowTopic === topic) {

        const rowIndex = i + 2;
        progressSheet.getRange(rowIndex, 7).setValue(status);
        progressSheet.getRange(rowIndex, 8).setValue(trainerEmail);
        progressSheet.getRange(rowIndex, 9).setValue(new Date());
        rowFound = true;
        break;
      }
    }

    if (!rowFound) {
      const iltSheet = ss.getSheetByName('ILT');
      let traineeName = '';
      let startDate = '';
      let endDate = '';

      if (iltSheet && iltSheet.getLastRow() > 1) {
        const iltData = iltSheet.getRange(2, 1, iltSheet.getLastRow() - 1, 9).getValues();
        for (const row of iltData) {
          if (String(row[4]).toLowerCase().trim() === String(traineeEmail).toLowerCase() &&
            String(row[0]).trim() === batch) {
            traineeName = row[3];
            startDate = row[6] instanceof Date ? Utilities.formatDate(row[6], Session.getScriptTimeZone(), 'yyyy-MM-dd') : row[6];
            endDate = row[7] instanceof Date ? Utilities.formatDate(row[7], Session.getScriptTimeZone(), 'yyyy-MM-dd') : row[7];
            break;
          }
        }
      }

      progressSheet.appendRow([
        traineeEmail,
        traineeName,
        batch,
        application,
        day,
        topic,
        status,
        trainerEmail,
        new Date(),
        startDate,
        endDate
      ]);
    }

    return { success: true, message: `Topic marked as ${status}` };
  } catch (error) {
    console.error('Error marking topic status:', error);
    return { success: false, message: error.message };
  }
}

function getTraineeProgressSummary(traineeEmail) {
  try {
    const ss = getSpreadsheet();
    const iltSheet = ss.getSheetByName('ILT');
    const progressSheet = ss.getSheetByName('Training_Progress');

    if (!iltSheet || iltSheet.getLastRow() < 2) {
      return { trainings: [] };
    }

    const iltData = iltSheet.getRange(2, 1, iltSheet.getLastRow() - 1, 9).getValues();
    const trainingsMap = {};

    iltData.forEach(row => {
      const rowEmail = String(row[4]).toLowerCase().trim();
      if (rowEmail !== String(traineeEmail).toLowerCase()) return;

      const key = `${row[0]}|${row[2]}`;

      if (!trainingsMap[key]) {
        let startDate = row[6];
        let endDate = row[7];

        if (startDate instanceof Date) startDate = Utilities.formatDate(startDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');
        if (endDate instanceof Date) endDate = Utilities.formatDate(endDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');

        trainingsMap[key] = {
          batch: row[0],
          application: row[2],
          startDate: startDate,
          endDate: endDate,
          level: row[5],
          totalTopics: 0,
          completedTopics: 0
        };
      }
    });

    if (progressSheet && progressSheet.getLastRow() > 1) {
      const progressData = progressSheet.getRange(2, 1, progressSheet.getLastRow() - 1, 11).getValues();

      progressData.forEach(row => {
        const rowEmail = String(row[0]).toLowerCase().trim();
        if (rowEmail !== String(traineeEmail).toLowerCase()) return;

        const key = `${row[2]}|${row[3]}`;

        if (trainingsMap[key]) {
          trainingsMap[key].totalTopics++;
          if (row[6] === 'Done') trainingsMap[key].completedTopics++;
        }
      });
    }

    const trainings = Object.values(trainingsMap).map(t => ({
      ...t,
      progressPercent: t.totalTopics > 0 ? Math.round((t.completedTopics / t.totalTopics) * 100) : 0
    }));

    return { trainings: trainings };
  } catch (error) {
    console.error('Error getting trainee progress summary:', error);
    return { trainings: [], error: error.message };
  }
}

// ==================== CATEGORY-SPECIFIC FUNCTIONS ====================

function getCategoryApplications(categoryName) {
  try {
    const ss = getSpreadsheet();
    const defaultCategories = ['ilt', 'sbl', 'isms', 'misc'];
    const isDefaultCategory = defaultCategories.includes(categoryName.toLowerCase());
    const sheetName = isDefaultCategory ? 'ILT' : categoryName;
    const sheet = ss.getSheetByName(sheetName);

    if (!sheet || sheet.getLastRow() < 2) {
      return [];
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 9).getValues();
    const apps = new Set();

    data.forEach(row => {
      const rowCategory = String(row[1]).trim().toLowerCase();
      if (!isDefaultCategory || rowCategory === String(categoryName).trim().toLowerCase()) {
        if (row[2]) apps.add(String(row[2]).trim());
      }
    });

    return [...apps].sort();
  } catch (error) {
    console.error('Error getting category applications:', error);
    return [];
  }
}

function getCategoryTrainees(categoryName) {
  try {
    const ss = getSpreadsheet();
    const defaultCategories = ['ilt', 'sbl', 'isms', 'misc'];
    const isDefaultCategory = defaultCategories.includes(categoryName.toLowerCase());
    const sheetName = isDefaultCategory ? 'ILT' : categoryName;
    const sheet = ss.getSheetByName(sheetName);

    if (!sheet || sheet.getLastRow() < 2) {
      return [];
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 9).getValues();
    const traineesMap = {};

    data.forEach(row => {
      const rowCategory = String(row[1]).trim().toLowerCase();
      if (!isDefaultCategory || rowCategory === String(categoryName).trim().toLowerCase()) {
        const email = String(row[4]).toLowerCase().trim();
        if (email && !traineesMap[email]) {
          traineesMap[email] = {
            name: String(row[3]).trim(),
            email: email
          };
        }
      }
    });

    return Object.values(traineesMap).sort((a, b) => a.name.localeCompare(b.name));
  } catch (error) {
    console.error('Error getting category trainees:', error);
    return [];
  }
}

function getCategoryTrainingsForTrainer(filters) {
  try {
    const ss = getSpreadsheet();
    const categoryName = filters.category;
    const defaultCategories = ['ilt', 'sbl', 'isms', 'misc'];
    const isDefaultCategory = defaultCategories.includes(categoryName.toLowerCase());
    const sheetName = isDefaultCategory ? 'ILT' : categoryName;
    const sheet = ss.getSheetByName(sheetName);

    if (!sheet || sheet.getLastRow() < 2) {
      return { trainings: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 9).getValues();
    const trainingsMap = {};

    data.forEach(row => {
      if (!row[0]) return;

      const rowCategory = String(row[1]).trim().toLowerCase();
      if (isDefaultCategory && rowCategory !== String(categoryName).trim().toLowerCase()) return;

      const traineeEmail = String(row[4]).toLowerCase().trim();
      const traineeName = String(row[3]).trim();
      const application = String(row[2]).trim();
      const batch = String(row[0]).trim();
      let startDate = row[6];
      let endDate = row[7];

      if (filters.traineeName && !traineeName.toLowerCase().includes(filters.traineeName.toLowerCase())) return;
      if (filters.application && application !== filters.application) return;
      if (filters.startDate) {
        const filterStart = new Date(filters.startDate);
        const rowStart = new Date(startDate);
        if (rowStart < filterStart) return;
      }
      if (filters.endDate) {
        const filterEnd = new Date(filters.endDate);
        const rowEnd = new Date(endDate);
        if (rowEnd > filterEnd) return;
      }

      if (startDate instanceof Date) startDate = Utilities.formatDate(startDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');
      if (endDate instanceof Date) endDate = Utilities.formatDate(endDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');

      const key = `${batch}|${application}|${traineeEmail}`;

      if (!trainingsMap[key]) {
        trainingsMap[key] = {
          batch: batch,
          application: application,
          traineeEmail: traineeEmail,
          traineeName: traineeName,
          startDate: startDate,
          endDate: endDate,
          level: row[5]
        };
      }
    });

    return { trainings: Object.values(trainingsMap) };
  } catch (error) {
    console.error('Error getting category trainings for trainer:', error);
    return { trainings: [] };
  }
}

function getCategoryTraineeProgressSummary(traineeEmail, categoryName) {
  try {
    const ss = getSpreadsheet();
    const defaultCategories = ['ilt', 'sbl', 'isms', 'misc'];
    const isDefaultCategory = defaultCategories.includes(categoryName.toLowerCase());
    const sheetName = isDefaultCategory ? 'ILT' : categoryName;
    const categorySheet = ss.getSheetByName(sheetName);
    const progressSheet = ss.getSheetByName('Training_Progress');

    if (!categorySheet || categorySheet.getLastRow() < 2) {
      return { trainings: [] };
    }

    const catData = categorySheet.getRange(2, 1, categorySheet.getLastRow() - 1, 9).getValues();
    const trainingsMap = {};

    catData.forEach(row => {
      const rowEmail = String(row[4]).toLowerCase().trim();
      const rowCategory = String(row[1]).trim().toLowerCase();

      if (rowEmail !== String(traineeEmail).toLowerCase()) return;
      if (isDefaultCategory && rowCategory !== String(categoryName).trim().toLowerCase()) return;

      const key = `${row[0]}|${row[2]}`;

      if (!trainingsMap[key]) {
        let startDate = row[6];
        let endDate = row[7];

        if (startDate instanceof Date) startDate = Utilities.formatDate(startDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');
        if (endDate instanceof Date) endDate = Utilities.formatDate(endDate, Session.getScriptTimeZone(), 'yyyy-MM-dd');

        trainingsMap[key] = {
          batch: row[0],
          application: row[2],
          startDate: startDate,
          endDate: endDate,
          level: row[5],
          totalTopics: 0,
          completedTopics: 0
        };
      }
    });

    if (progressSheet && progressSheet.getLastRow() > 1) {
      const progressData = progressSheet.getRange(2, 1, progressSheet.getLastRow() - 1, 11).getValues();

      progressData.forEach(row => {
        const rowEmail = String(row[0]).toLowerCase().trim();
        if (rowEmail !== String(traineeEmail).toLowerCase()) return;

        const key = `${row[2]}|${row[3]}`;

        if (trainingsMap[key]) {
          trainingsMap[key].totalTopics++;
          if (row[6] === 'Done') trainingsMap[key].completedTopics++;
        }
      });
    }

    const trainings = Object.values(trainingsMap).map(t => ({
      ...t,
      progressPercent: t.totalTopics > 0 ? Math.round((t.completedTopics / t.totalTopics) * 100) : 0
    }));

    return { trainings: trainings };
  } catch (error) {
    console.error('Error getting category trainee progress summary:', error);
    return { trainings: [], error: error.message };
  }
}

function getCategoryEvaluationsData(userEmail, categoryName) {
  try {
    const ss = getSpreadsheet();
    const evalSheet = ss.getSheetByName('ILT_Evaluations');

    const defaultCategories = ['ilt', 'sbl', 'isms', 'misc'];
    const isDefaultCategory = defaultCategories.includes(categoryName.toLowerCase());
    const categorySheetName = isDefaultCategory ? 'ILT' : categoryName;
    const categorySheet = ss.getSheetByName(categorySheetName);

    if (!evalSheet || evalSheet.getLastRow() < 2) {
      return { evaluations: [] };
    }

    const categoryTrainees = new Set();
    const categoryApplications = new Set();

    if (categorySheet && categorySheet.getLastRow() > 1) {
      const catData = categorySheet.getRange(2, 1, categorySheet.getLastRow() - 1, 9).getValues();
      catData.forEach(row => {
        const rowCategory = String(row[1]).trim().toLowerCase();
        if (!isDefaultCategory || rowCategory === String(categoryName).trim().toLowerCase()) {
          categoryTrainees.add(String(row[4]).toLowerCase().trim());
          categoryApplications.add(String(row[2]).trim());
        }
      });
    }

    const data = evalSheet.getRange(2, 1, evalSheet.getLastRow() - 1, 8).getValues();
    const evaluations = [];

    data.forEach(row => {
      const traineeEmail = String(row[2]).toLowerCase().trim();
      const trainingName = String(row[1]).trim();

      if (!categoryTrainees.has(traineeEmail) && !categoryApplications.has(trainingName)) return;

      if (userEmail && traineeEmail !== String(userEmail).toLowerCase()) return;

      evaluations.push({
        training: trainingName,
        date: row[4] ? Utilities.formatDate(new Date(row[4]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
        score: row[5] || '-',
        evaluator: row[3] || '-',
        status: row[7] || 'Pending'
      });
    });

    return { evaluations: evaluations };
  } catch (error) {
    console.error('Error getting category evaluations data:', error);
    return { evaluations: [] };
  }
}

function getCategoryReportsData(categoryName) {
  try {
    const ss = getSpreadsheet();
    const certSheet = ss.getSheetByName('ILT_Certifications');

    const defaultCategories = ['ilt', 'sbl', 'isms', 'misc'];
    const isDefaultCategory = defaultCategories.includes(categoryName.toLowerCase());
    const categorySheetName = isDefaultCategory ? 'ILT' : categoryName;
    const categorySheet = ss.getSheetByName(categorySheetName);

    if (!certSheet || certSheet.getLastRow() < 2) {
      return { certifications: [] };
    }

    const categoryTrainees = new Set();
    const categoryApplications = new Set();

    if (categorySheet && categorySheet.getLastRow() > 1) {
      const catData = categorySheet.getRange(2, 1, categorySheet.getLastRow() - 1, 9).getValues();
      catData.forEach(row => {
        const rowCategory = String(row[1]).trim().toLowerCase();
        if (!isDefaultCategory || rowCategory === String(categoryName).trim().toLowerCase()) {
          categoryTrainees.add(String(row[4]).toLowerCase().trim());
          categoryApplications.add(String(row[2]).trim());
        }
      });
    }

    const data = certSheet.getRange(2, 1, certSheet.getLastRow() - 1, 7).getValues();
    const certifications = [];

    data.forEach(row => {
      const trainingName = String(row[1]).trim();
      const traineeEmail = String(row[2]).toLowerCase().trim();

      if (!categoryTrainees.has(traineeEmail) && !categoryApplications.has(trainingName)) return;

      certifications.push({
        trainee: row[3] || '-',
        training: trainingName,
        certDate: row[4] ? Utilities.formatDate(new Date(row[4]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
        expiryDate: row[5] ? Utilities.formatDate(new Date(row[5]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
        status: row[6] || 'Active'
      });
    });

    return { certifications: certifications };
  } catch (error) {
    console.error('Error getting category reports data:', error);
    return { certifications: [] };
  }
}


// =====================================================================================
// QUIZ EVALUATION MODULE
// =====================================================================================

function initializeQuizSheets() {
  const ss = getSpreadsheet();

  let assignSheet = ss.getSheetByName(ASSIGNED_QUIZ_SHEET_NAME);
  if (!assignSheet) {
    assignSheet = ss.insertSheet(ASSIGNED_QUIZ_SHEET_NAME);
    const assignHeaders = [
      'Assignment ID', 'Batch', 'Trainee Email', 'Trainee Name',
      'Application', 'Test Number', 'Assigned By', 'Assigned Date',
      'Status', 'Due Date'
    ];
    assignSheet.getRange(1, 1, 1, assignHeaders.length).setValues([assignHeaders]);
    assignSheet.getRange(1, 1, 1, assignHeaders.length).setFontWeight('bold');
    assignSheet.getRange(1, 1, 1, assignHeaders.length).setBackground('#4285f4');
    assignSheet.getRange(1, 1, 1, assignHeaders.length).setFontColor('#ffffff');
    assignSheet.setFrozenRows(1);
  }

  let resultsSheet = ss.getSheetByName(QUIZ_RESULTS_SHEET_NAME);
  if (!resultsSheet) {
    resultsSheet = ss.insertSheet(QUIZ_RESULTS_SHEET_NAME);
    const resultsHeaders = [
      'Result ID', 'Assignment ID', 'Batch', 'Trainee Email', 'Trainee Name',
      'Application', 'Test Number', 'Total Questions', 'Correct Answers',
      'Score Percentage', 'Submitted Date', 'Time Taken (mins)', 'Answers JSON'
    ];
    resultsSheet.getRange(1, 1, 1, resultsHeaders.length).setValues([resultsHeaders]);
    resultsSheet.getRange(1, 1, 1, resultsHeaders.length).setFontWeight('bold');
    resultsSheet.getRange(1, 1, 1, resultsHeaders.length).setBackground('#34a853');
    resultsSheet.getRange(1, 1, 1, resultsHeaders.length).setFontColor('#ffffff');
    resultsSheet.setFrozenRows(1);
  }

  return { success: true, message: 'Quiz sheets initialized successfully' };
}

function getQuizApplications() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName(QUIZ_SHEET_NAME);
    if (!sheet || sheet.getLastRow() < 2) return [];
    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 1).getValues();
    const apps = new Set();
    data.forEach(row => { if (row[0] && String(row[0]).trim()) apps.add(String(row[0]).trim()); });
    return [...apps].sort();
  } catch (error) { console.error('Error getting quiz applications:', error); return []; }
}

function getQuizTestNumbers(application) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName(QUIZ_SHEET_NAME);
    if (!sheet || sheet.getLastRow() < 2) return [];
    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 2).getValues();
    const testNumbers = new Set();
    data.forEach(row => {
      if (String(row[0]).trim().toLowerCase() === String(application).trim().toLowerCase()) {
        if (row[1] && String(row[1]).trim()) testNumbers.add(String(row[1]).trim());
      }
    });
    return [...testNumbers].sort();
  } catch (error) { console.error('Error getting quiz test numbers:', error); return []; }
}

function getAllBatches() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('ILT');
    if (!sheet || sheet.getLastRow() < 2) return [];
    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 1).getValues();
    const batches = new Set();
    data.forEach(row => { if (row[0] && String(row[0]).trim()) batches.add(String(row[0]).trim()); });
    return [...batches].sort((a, b) => {
      const numA = parseInt(String(a).replace(/\D/g, ''), 10) || 0;
      const numB = parseInt(String(b).replace(/\D/g, ''), 10) || 0;
      return numA - numB;
    });
  } catch (error) { console.error('Error getting all batches:', error); return []; }
}

function getAllTrainees() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName(LOGIN_SHEET_NAME);
    if (!sheet || sheet.getLastRow() < 2) return [];
    const data = sheet.getDataRange().getValues();
    const trainees = [];
    for (let i = 1; i < data.length; i++) {
      const userType = String(data[i][6]).trim().toLowerCase();
      if (userType === 'trainee') {
        trainees.push({ name: String(data[i][0]).trim(), email: String(data[i][1]).trim() });
      }
    }
    return trainees.sort((a, b) => a.name.localeCompare(b.name));
  } catch (error) { console.error('Error getting all trainees:', error); return []; }
}

function getTraineesForBatch(batch) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('ILT');
    if (!sheet || sheet.getLastRow() < 2) return [];
    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 5).getValues();
    const traineesMap = {};
    data.forEach(row => {
      if (String(row[0]).trim() === String(batch).trim()) {
        const email = String(row[4]).trim().toLowerCase();
        if (email && !traineesMap[email]) {
          traineesMap[email] = { name: String(row[3]).trim(), email: String(row[4]).trim() };
        }
      }
    });
    return Object.values(traineesMap).sort((a, b) => a.name.localeCompare(b.name));
  } catch (error) { console.error('Error getting trainees for batch:', error); return []; }
}

function assignQuizToTrainees(assignmentData) {
  try {
    initializeQuizSheets();
    const ss = getSpreadsheet();
    const assignSheet = ss.getSheetByName(ASSIGNED_QUIZ_SHEET_NAME);
    const loginSheet = ss.getSheetByName(LOGIN_SHEET_NAME);
    const loginData = loginSheet.getDataRange().getValues();
    const traineeNames = {};
    for (let i = 1; i < loginData.length; i++) {
      traineeNames[String(loginData[i][1]).toLowerCase().trim()] = String(loginData[i][0]).trim();
    }
    const lastRow = assignSheet.getLastRow();
    let nextId = 1;
    if (lastRow > 1) {
      const lastId = assignSheet.getRange(lastRow, 1).getValue();
      const idNum = parseInt(String(lastId).replace('QA', '')) || 0;
      nextId = idNum + 1;
    }
    const rowsToAdd = [];
    const assignedDate = new Date();
    assignmentData.traineeEmails.forEach((email, index) => {
      const assignmentId = 'QA' + String(nextId + index).padStart(5, '0');
      const traineeName = traineeNames[email.toLowerCase().trim()] || email;
      rowsToAdd.push([
        assignmentId, assignmentData.batch || '', email, traineeName,
        assignmentData.application, assignmentData.testNumber,
        assignmentData.assignedBy, assignedDate, 'Pending', assignmentData.dueDate || ''
      ]);
    });
    if (rowsToAdd.length > 0) {
      assignSheet.getRange(lastRow + 1, 1, rowsToAdd.length, 10).setValues(rowsToAdd);
    }
    return { success: true, message: `Quiz assigned to ${rowsToAdd.length} trainee(s) successfully` };
  } catch (error) { console.error('Error assigning quiz:', error); return { success: false, message: error.message }; }
}

function getPendingQuizzesForTrainee(traineeEmail) {
  try {
    initializeQuizSheets();
    const ss = getSpreadsheet();
    const assignSheet = ss.getSheetByName(ASSIGNED_QUIZ_SHEET_NAME);
    const quizSheet = ss.getSheetByName(QUIZ_SHEET_NAME);
    if (!assignSheet || assignSheet.getLastRow() < 2) return { quizzes: [] };
    const quizData = quizSheet.getRange(2, 1, quizSheet.getLastRow() - 1, 2).getValues();
    const questionCounts = {};
    quizData.forEach(row => {
      const app = String(row[0]).trim().toLowerCase();
      const test = String(row[1]).trim().toLowerCase();
      const key = app + '|' + test;
      questionCounts[key] = (questionCounts[key] || 0) + 1;
    });
    const data = assignSheet.getRange(2, 1, assignSheet.getLastRow() - 1, 10).getValues();
    const quizzes = [];
    data.forEach((row, index) => {
      const email = String(row[2]).toLowerCase().trim();
      const status = String(row[8]).trim();
      if (email === String(traineeEmail).toLowerCase().trim() && status === 'Pending') {
        const application = row[4];
        const testNumber = row[5];
        const key = String(application).trim().toLowerCase() + '|' + String(testNumber).trim().toLowerCase();
        quizzes.push({
          assignmentId: row[0], batch: row[1], application: application, testNumber: testNumber,
          assignedBy: row[6],
          assignedDate: row[7] ? Utilities.formatDate(new Date(row[7]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
          dueDate: row[9] ? Utilities.formatDate(new Date(row[9]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
          questionCount: questionCounts[key] || 0, rowIndex: index + 2
        });
      }
    });
    return { quizzes: quizzes };
  } catch (error) { console.error('Error getting pending quizzes:', error); return { quizzes: [], error: error.message }; }
}

function getQuizAssignmentsForTrainer(filters) {
  try {
    initializeQuizSheets();
    const ss = getSpreadsheet();
    const assignSheet = ss.getSheetByName(ASSIGNED_QUIZ_SHEET_NAME);
    if (!assignSheet || assignSheet.getLastRow() < 2) return { assignments: [] };
    const data = assignSheet.getRange(2, 1, assignSheet.getLastRow() - 1, 10).getValues();
    const assignments = [];
    data.forEach(row => {
      const batch = String(row[1]).trim();
      const application = String(row[4]).trim();
      const status = String(row[8]).trim();
      if (filters) {
        if (filters.batch && batch !== filters.batch) return;
        if (filters.application && application !== filters.application) return;
        if (filters.status && status !== filters.status) return;
      }
      assignments.push({
        assignmentId: row[0], batch: batch, traineeEmail: row[2], traineeName: row[3],
        application: application, testNumber: row[5], assignedBy: row[6],
        assignedDate: row[7] ? Utilities.formatDate(new Date(row[7]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-',
        status: status,
        dueDate: row[9] ? Utilities.formatDate(new Date(row[9]), Session.getScriptTimeZone(), 'yyyy-MM-dd') : '-'
      });
    });
    assignments.sort((a, b) => new Date(b.assignedDate) - new Date(a.assignedDate));
    return { assignments: assignments };
  } catch (error) { console.error('Error getting quiz assignments:', error); return { assignments: [], error: error.message }; }
}

function getQuizQuestions(application, testNumber) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName(QUIZ_SHEET_NAME);
    if (!sheet || sheet.getLastRow() < 2) return { success: false, message: 'Quiz sheet not found or empty', questions: [] };
    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 8).getValues();
    const questions = [];
    data.forEach((row, index) => {
      const rowApp = String(row[0]).trim().toLowerCase();
      const rowTest = String(row[1]).trim().toLowerCase();
      if (rowApp === String(application).trim().toLowerCase() && rowTest === String(testNumber).trim().toLowerCase()) {
        questions.push({ questionId: index + 2, question: row[2], optionA: row[3], optionB: row[4], optionC: row[5], optionD: row[6] });
      }
    });
    if (questions.length === 0) return { success: false, message: 'No questions found for ' + application + ' - ' + testNumber, questions: [] };
    for (let i = questions.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [questions[i], questions[j]] = [questions[j], questions[i]];
    }
    return { success: true, questions: questions };
  } catch (error) { console.error('Error getting quiz questions:', error); return { success: false, message: error.message, questions: [] }; }
}

function submitQuizAnswers(submissionData) {
  try {
    initializeQuizSheets();
    const ss = getSpreadsheet();
    const quizSheet = ss.getSheetByName(QUIZ_SHEET_NAME);
    const assignSheet = ss.getSheetByName(ASSIGNED_QUIZ_SHEET_NAME);
    const resultsSheet = ss.getSheetByName(QUIZ_RESULTS_SHEET_NAME);
    if (!quizSheet || !assignSheet || !resultsSheet) return { success: false, message: 'Required sheets not found' };
    const quizData = quizSheet.getRange(2, 1, quizSheet.getLastRow() - 1, 8).getValues();
    const correctAnswers = {};
    quizData.forEach((row, index) => {
      const rowApp = String(row[0]).trim().toLowerCase();
      const rowTest = String(row[1]).trim().toLowerCase();
      if (rowApp === String(submissionData.application).trim().toLowerCase() && rowTest === String(submissionData.testNumber).trim().toLowerCase()) {
        correctAnswers[index + 2] = String(row[7]).trim().toUpperCase();
      }
    });
    let correctCount = 0;
    const totalQuestions = Object.keys(submissionData.answers).length;
    const answerDetails = [];
    for (const [questionId, answer] of Object.entries(submissionData.answers)) {
      const correctAnswer = correctAnswers[parseInt(questionId)];
      const isCorrect = String(answer).trim().toUpperCase() === correctAnswer;
      if (isCorrect) correctCount++;
      answerDetails.push({ questionId: questionId, userAnswer: answer, correctAnswer: correctAnswer, isCorrect: isCorrect });
    }
    const scorePercentage = totalQuestions > 0 ? Math.round((correctCount / totalQuestions) * 100) : 0;
    const lastResultRow = resultsSheet.getLastRow();
    let nextResultId = 1;
    if (lastResultRow > 1) {
      const lastId = resultsSheet.getRange(lastResultRow, 1).getValue();
      const idNum = parseInt(String(lastId).replace('QR', '')) || 0;
      nextResultId = idNum + 1;
    }
    const resultId = 'QR' + String(nextResultId).padStart(5, '0');
    const submittedDate = new Date();
    resultsSheet.appendRow([
      resultId, submissionData.assignmentId, submissionData.batch, submissionData.traineeEmail,
      submissionData.traineeName, submissionData.application, submissionData.testNumber,
      totalQuestions, correctCount, scorePercentage, submittedDate, submissionData.timeTaken || 0,
      JSON.stringify(answerDetails)
    ]);
    const assignData = assignSheet.getRange(2, 1, assignSheet.getLastRow() - 1, 10).getValues();
    for (let i = 0; i < assignData.length; i++) {
      if (assignData[i][0] === submissionData.assignmentId) {
        assignSheet.getRange(i + 2, 9).setValue('Completed');
        break;
      }
    }
    return { success: true, message: 'Quiz submitted successfully', resultId: resultId, totalQuestions: totalQuestions, correctAnswers: correctCount, scorePercentage: scorePercentage, answerDetails: answerDetails };
  } catch (error) { console.error('Error submitting quiz:', error); return { success: false, message: error.message }; }
}

function getQuizResultsForTrainer(filters) {
  try {
    initializeQuizSheets();
    const ss = getSpreadsheet();
    const resultsSheet = ss.getSheetByName(QUIZ_RESULTS_SHEET_NAME);
    if (!resultsSheet || resultsSheet.getLastRow() < 2) return { results: [] };
    const data = resultsSheet.getRange(2, 1, resultsSheet.getLastRow() - 1, 13).getValues();
    const results = [];
    data.forEach(row => {
      const batch = String(row[2]).trim();
      const application = String(row[5]).trim();
      const testNumber = String(row[6]).trim();
      if (filters) {
        if (filters.batch && batch !== filters.batch) return;
        if (filters.application && application !== filters.application) return;
        if (filters.testNumber && testNumber !== filters.testNumber) return;
        if (filters.traineeEmail && String(row[3]).toLowerCase() !== String(filters.traineeEmail).toLowerCase()) return;
      }
      results.push({
        resultId: row[0], assignmentId: row[1], batch: batch, traineeEmail: row[3], traineeName: row[4],
        application: application, testNumber: testNumber, totalQuestions: row[7], correctAnswers: row[8],
        scorePercentage: row[9],
        submittedDate: row[10] ? Utilities.formatDate(new Date(row[10]), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm') : '-',
        timeTaken: row[11], answerDetails: row[12] ? JSON.parse(row[12]) : []
      });
    });
    results.sort((a, b) => new Date(b.submittedDate) - new Date(a.submittedDate));
    return { results: results };
  } catch (error) { console.error('Error getting quiz results:', error); return { results: [], error: error.message }; }
}

function getQuizResultDetails(resultId) {
  try {
    const ss = getSpreadsheet();
    const resultsSheet = ss.getSheetByName(QUIZ_RESULTS_SHEET_NAME);
    const quizSheet = ss.getSheetByName(QUIZ_SHEET_NAME);
    if (!resultsSheet || resultsSheet.getLastRow() < 2) return { success: false, message: 'No results found' };
    const data = resultsSheet.getRange(2, 1, resultsSheet.getLastRow() - 1, 13).getValues();
    let result = null;
    for (const row of data) {
      if (row[0] === resultId) {
        result = {
          resultId: row[0], assignmentId: row[1], batch: row[2], traineeEmail: row[3], traineeName: row[4],
          application: row[5], testNumber: row[6], totalQuestions: row[7], correctAnswers: row[8],
          scorePercentage: row[9],
          submittedDate: row[10] ? Utilities.formatDate(new Date(row[10]), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm') : '-',
          timeTaken: row[11], answerDetails: row[12] ? JSON.parse(row[12]) : []
        };
        break;
      }
    }
    if (!result) return { success: false, message: 'Result not found' };
    const quizData = quizSheet.getRange(2, 1, quizSheet.getLastRow() - 1, 8).getValues();
    const questionMap = {};
    quizData.forEach((row, index) => {
      questionMap[index + 2] = { question: row[2], optionA: row[3], optionB: row[4], optionC: row[5], optionD: row[6], correctAnswer: row[7] };
    });
    result.answerDetails = result.answerDetails.map(detail => {
      const questionInfo = questionMap[parseInt(detail.questionId)] || {};
      return { ...detail, questionText: questionInfo.question || '', optionA: questionInfo.optionA || '', optionB: questionInfo.optionB || '', optionC: questionInfo.optionC || '', optionD: questionInfo.optionD || '' };
    });
    return { success: true, result: result };
  } catch (error) { console.error('Error getting quiz result details:', error); return { success: false, message: error.message }; }
}

function getQuizStatistics() {
  try {
    initializeQuizSheets();
    const ss = getSpreadsheet();
    const assignSheet = ss.getSheetByName(ASSIGNED_QUIZ_SHEET_NAME);
    const resultsSheet = ss.getSheetByName(QUIZ_RESULTS_SHEET_NAME);
    let totalAssigned = 0, pendingCount = 0, completedCount = 0, averageScore = 0;
    if (assignSheet && assignSheet.getLastRow() > 1) {
      const assignData = assignSheet.getRange(2, 9, assignSheet.getLastRow() - 1, 1).getValues();
      totalAssigned = assignData.length;
      assignData.forEach(row => {
        if (String(row[0]).trim() === 'Pending') pendingCount++;
        if (String(row[0]).trim() === 'Completed') completedCount++;
      });
    }
    if (resultsSheet && resultsSheet.getLastRow() > 1) {
      const resultsData = resultsSheet.getRange(2, 10, resultsSheet.getLastRow() - 1, 1).getValues();
      let totalScore = 0;
      resultsData.forEach(row => { totalScore += Number(row[0]) || 0; });
      averageScore = resultsData.length > 0 ? Math.round(totalScore / resultsData.length) : 0;
    }
    return { totalAssigned: totalAssigned, pendingCount: pendingCount, completedCount: completedCount, averageScore: averageScore };
  } catch (error) { console.error('Error getting quiz statistics:', error); return { totalAssigned: 0, pendingCount: 0, completedCount: 0, averageScore: 0 }; }
}

function getQuizCountForTrainee(traineeEmail) {
  try {
    initializeQuizSheets();
    const ss = getSpreadsheet();
    const assignSheet = ss.getSheetByName(ASSIGNED_QUIZ_SHEET_NAME);
    let pendingCount = 0, completedCount = 0;
    if (assignSheet && assignSheet.getLastRow() > 1) {
      const data = assignSheet.getRange(2, 3, assignSheet.getLastRow() - 1, 7).getValues();
      data.forEach(row => {
        if (String(row[0]).toLowerCase().trim() === String(traineeEmail).toLowerCase().trim()) {
          if (String(row[6]).trim() === 'Pending') pendingCount++;
          if (String(row[6]).trim() === 'Completed') completedCount++;
        }
      });
    }
    return { pendingCount: pendingCount, completedCount: completedCount };
  } catch (error) { console.error('Error getting quiz count:', error); return { pendingCount: 0, completedCount: 0 }; }
}

function exportQuizResultsCSV(filters) {
  try {
    const data = getQuizResultsForTrainer(filters);
    const results = data.results || [];
    if (results.length === 0) return 'No data to export';
    const headers = ['Batch', 'Trainee Name', 'Trainee Email', 'Application', 'Test Number', 'Total Questions', 'Correct Answers', 'Score %', 'Status', 'Submitted Date', 'Time Taken'];
    let csv = headers.join(',') + '\n';
    results.forEach(r => {
      const status = r.scorePercentage >= 70 ? 'Passed' : 'Failed';
      const timeTaken = r.timeTaken ? Math.floor(r.timeTaken / 60) + 'm ' + (r.timeTaken % 60) + 's' : '-';
      csv += [r.batch || '-', '"' + (r.traineeName || '-').replace(/"/g, '""') + '"', r.traineeEmail || '-', '"' + (r.application || '-').replace(/"/g, '""') + '"', r.testNumber || '-', r.totalQuestions || 0, r.correctAnswers || 0, r.scorePercentage || 0, status, r.submittedDate || '-', timeTaken].join(',') + '\n';
    });
    return csv;
  } catch (error) { console.error('Error exporting quiz results:', error); return 'Error exporting data: ' + error.message; }
}

// =====================================================================================
// ENHANCED REPORTS AND CERTIFICATION FUNCTIONS
// =====================================================================================

function getReportsAndCertificationData(filters) {
  try {
    initializeQuizSheets();
    const ss = getSpreadsheet();
    const resultsSheet = ss.getSheetByName(QUIZ_RESULTS_SHEET_NAME);
    const assignSheet = ss.getSheetByName(ASSIGNED_QUIZ_SHEET_NAME);
    const response = {
      tiles: { totalEvaluations: 0, totalPassed: 0, totalFailed: 0, totalCertifications: 0 },
      reports: [], certifications: [],
      filterOptions: { batches: [], testNumbers: [], applications: [] }
    };
    try {
      const certSheet = ss.getSheetByName('Individual_Certifications');
      if (certSheet && certSheet.getLastRow() >= 2) {
        const certData = certSheet.getRange(2, 1, certSheet.getLastRow() - 1, 9).getValues();
        certData.forEach(row => {
          response.certifications.push({
            certificateId: row[0], employeeName: row[1], email: row[2], batchNumber: row[3],
            application: row[4], issueDate: formatDateForDisplay(row[5]), expiryDate: formatDateForDisplay(row[6]),
            issuedBy: row[7], createdAt: row[8]
          });
        });
        response.tiles.totalCertifications = response.certifications.length;
      }
    } catch (certError) { console.log('Certifications sheet not found or error:', certError); }
    if (assignSheet && assignSheet.getLastRow() > 1) {
      const assignData = assignSheet.getRange(2, 1, assignSheet.getLastRow() - 1, 10).getValues();
      const batchSet = new Set(), testSet = new Set(), appSet = new Set();
      assignData.forEach(row => {
        if (row[1] && String(row[1]).trim()) batchSet.add(String(row[1]).trim());
        if (row[5] && String(row[5]).trim()) testSet.add(String(row[5]).trim());
        if (row[4] && String(row[4]).trim()) appSet.add(String(row[4]).trim());
      });
      response.filterOptions.batches = [...batchSet].sort((a, b) => { return (parseInt(String(a).replace(/\D/g, ''), 10) || 0) - (parseInt(String(b).replace(/\D/g, ''), 10) || 0); });
      response.filterOptions.testNumbers = [...testSet].sort();
      response.filterOptions.applications = [...appSet].sort();
    }
    if (!resultsSheet || resultsSheet.getLastRow() < 2) return response;
    const data = resultsSheet.getRange(2, 1, resultsSheet.getLastRow() - 1, 13).getValues();
    const passThreshold = 70;
    data.forEach(row => {
      const batch = String(row[2]).trim();
      const application = String(row[5]).trim();
      const testNumber = String(row[6]).trim();
      const scorePercentage = Number(row[9]) || 0;
      const submittedDate = row[10];
      let includeInReport = true;
      if (filters) {
        if (filters.batch && filters.batch !== '' && batch !== filters.batch) includeInReport = false;
        if (filters.testNumber && filters.testNumber !== '' && testNumber !== filters.testNumber) includeInReport = false;
        if (filters.application && filters.application !== '' && application !== filters.application) includeInReport = false;
        if (filters.startDate && submittedDate) { if (new Date(submittedDate) < new Date(filters.startDate)) includeInReport = false; }
        if (filters.endDate && submittedDate) { const filterEnd = new Date(filters.endDate); filterEnd.setHours(23, 59, 59, 999); if (new Date(submittedDate) > filterEnd) includeInReport = false; }
      }
      if (includeInReport) {
        const isPassed = scorePercentage >= passThreshold;
        response.tiles.totalEvaluations++;
        if (isPassed) response.tiles.totalPassed++; else response.tiles.totalFailed++;
        response.reports.push({
          resultId: row[0], batch: batch || '-', traineeName: row[4] || '-', traineeEmail: row[3] || '-',
          application: application, testNumber: testNumber, totalQuestions: row[7] || 0,
          correctAnswers: row[8] || 0, score: scorePercentage, status: isPassed ? 'Pass' : 'Fail',
          submittedDate: submittedDate ? Utilities.formatDate(new Date(submittedDate), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm') : '-',
          timeTaken: row[11] || 0
        });
      }
    });
    response.reports.sort((a, b) => { if (a.submittedDate === '-') return 1; if (b.submittedDate === '-') return -1; return new Date(b.submittedDate) - new Date(a.submittedDate); });
    return response;
  } catch (error) { console.error('Error getting reports and certification data:', error); return { tiles: { totalEvaluations: 0, totalPassed: 0, totalFailed: 0 }, reports: [], filterOptions: { batches: [], testNumbers: [], applications: [] }, error: error.message }; }
}

function getAssignedTestNumbers() {
  try {
    const ss = getSpreadsheet();
    const assignSheet = ss.getSheetByName(ASSIGNED_QUIZ_SHEET_NAME);
    if (!assignSheet || assignSheet.getLastRow() < 2) return [];
    const data = assignSheet.getRange(2, 6, assignSheet.getLastRow() - 1, 1).getValues();
    const testNumbers = new Set();
    data.forEach(row => { if (row[0] && String(row[0]).trim()) testNumbers.add(String(row[0]).trim()); });
    return [...testNumbers].sort();
  } catch (error) { console.error('Error getting assigned test numbers:', error); return []; }
}

function exportReportsCSV(filters) {
  try {
    const data = getReportsAndCertificationData(filters);
    const reports = data.reports || [];
    if (reports.length === 0) return 'No data to export';
    const headers = ['Batch', 'Name', 'Email', 'Application', 'Test Number', 'Total Questions', 'Correct Answers', 'Score (%)', 'Status', 'Submitted Date', 'Time Taken (seconds)'];
    let csv = headers.join(',') + '\n';
    reports.forEach(r => {
      csv += [r.batch || '-', '"' + (r.traineeName || '-').replace(/"/g, '""') + '"', r.traineeEmail || '-', '"' + (r.application || '-').replace(/"/g, '""') + '"', r.testNumber || '-', r.totalQuestions || 0, r.correctAnswers || 0, r.score || 0, r.status || '-', r.submittedDate || '-', r.timeTaken || 0].join(',') + '\n';
    });
    return csv;
  } catch (error) { console.error('Error exporting reports CSV:', error); return 'Error exporting data: ' + error.message; }
}

// ==================== INDIVIDUAL CERTIFICATION FUNCTIONS ====================

function initializeCertificationsSheet() {
  const ss = getSpreadsheet();
  let sheet = ss.getSheetByName('Individual_Certifications');
  if (!sheet) {
    sheet = ss.insertSheet('Individual_Certifications');
    sheet.appendRow(['Certificate ID', 'Employee Name', 'Email', 'Batch Number', 'Application', 'Issue Date', 'Expiry Date', 'Issued By', 'Created At']);
    sheet.getRange(1, 1, 1, 9).setFontWeight('bold').setBackground('#4285f4').setFontColor('white');
    sheet.setFrozenRows(1);
  }
  return sheet;
}

function getRegisteredTrainingEmployees() {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('ILT');
    if (!sheet || sheet.getLastRow() < 2) return [];
    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 9).getValues();
    const employeesMap = {};
    data.forEach(row => {
      const email = String(row[4]).toLowerCase().trim();
      const name = String(row[3]).trim();
      if (email && name && !employeesMap[email]) employeesMap[email] = { name: name, email: email };
    });
    return Object.values(employeesMap).sort((a, b) => a.name.localeCompare(b.name));
  } catch (error) { console.error('Error getting registered employees:', error); return []; }
}

function generateCertificateId() {
  const timestamp = new Date().getTime().toString(36).toUpperCase();
  const random = Math.random().toString(36).substring(2, 6).toUpperCase();
  return 'CERT-' + timestamp + '-' + random;
}

function generateIndividualCertification(certData) {
  try {
    const sheet = initializeCertificationsSheet();
    const certificateId = generateCertificateId();
    sheet.appendRow([certificateId, certData.employeeName, certData.email, certData.batchNumber, certData.application, certData.issueDate, certData.expiryDate, certData.issuedBy, new Date().toISOString()]);
    return { success: true, message: 'Certificate generated successfully', certificateId: certificateId };
  } catch (error) { console.error('Error generating certification:', error); return { success: false, message: 'Failed to generate certificate: ' + error.message }; }
}

function getAllCertifications(userEmail, userType) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('Individual_Certifications');
    if (!sheet || sheet.getLastRow() < 2) return [];
    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 9).getValues();
    const certifications = [];
    data.forEach(row => {
      const cert = { certificateId: row[0], employeeName: row[1], email: row[2], batchNumber: row[3], application: row[4], issueDate: formatDateForDisplay(row[5]), expiryDate: formatDateForDisplay(row[6]), issuedBy: row[7], createdAt: row[8] };
      const lowerUserType = (userType || '').toLowerCase().trim();
      if (lowerUserType === 'trainee') {
        if (String(cert.email).toLowerCase().trim() === String(userEmail).toLowerCase().trim()) certifications.push(cert);
      } else {
        certifications.push(cert);
      }
    });
    return certifications;
  } catch (error) { console.error('Error getting certifications:', error); return []; }
}

function formatDateForDisplay(date) {
  if (!date) return '';
  try {
    const d = new Date(date);
    if (isNaN(d.getTime())) return String(date);
    return d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
  } catch (e) { return String(date); }
}

function getCertificateHTML(certificateId) {
  try {
    const ss = getSpreadsheet();
    const sheet = ss.getSheetByName('Individual_Certifications');
    if (!sheet || sheet.getLastRow() < 2) return { success: false, message: 'Certificate not found' };
    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 9).getValues();
    let certData = null;
    for (let i = 0; i < data.length; i++) {
      if (data[i][0] === certificateId) {
        certData = { certificateId: data[i][0], employeeName: data[i][1], email: data[i][2], batchNumber: data[i][3], application: data[i][4], issueDate: formatDateForDisplay(data[i][5]), expiryDate: formatDateForDisplay(data[i][6]), issuedBy: data[i][7] };
        break;
      }
    }
    if (!certData) return { success: false, message: 'Certificate not found' };
    const logoUrl = 'https://learninganddevelopment.net/ANR/Logo/1.png';
    const html = '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Certificate - ' + certData.employeeName + '</title><style>@import url("https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=Open+Sans:wght@400;600&display=swap");*{margin:0;padding:0;box-sizing:border-box}body{font-family:"Open Sans",sans-serif;background:#f5f5f5;padding:20px}.certificate-container{width:900px;max-width:100%;margin:0 auto;background:white;position:relative;padding:40px;box-shadow:0 10px 40px rgba(0,0,0,.1)}.certificate-border{position:absolute;top:15px;left:15px;right:15px;bottom:15px;border:3px solid #1a237e;pointer-events:none}.certificate-border-inner{position:absolute;top:25px;left:25px;right:25px;bottom:25px;border:1px solid #c5a47e;pointer-events:none}.certificate-content{position:relative;z-index:1;text-align:center;padding:30px}.logo{width:120px;height:auto;margin-bottom:20px}.certificate-title{font-family:"Playfair Display",serif;font-size:42px;color:#1a237e;margin-bottom:10px;letter-spacing:3px}.certificate-subtitle{font-size:16px;color:#666;text-transform:uppercase;letter-spacing:5px;margin-bottom:30px}.presented-to{font-size:14px;color:#888;text-transform:uppercase;letter-spacing:2px;margin-bottom:10px}.recipient-name{font-family:"Playfair Display",serif;font-size:36px;color:#1a237e;margin-bottom:20px;font-weight:600}.certificate-text{font-size:16px;color:#444;line-height:1.8;max-width:700px;margin:0 auto 30px}.details-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:20px;max-width:600px;margin:30px auto;text-align:left}.detail-item{padding:15px;background:#f8f9fa;border-radius:8px}.detail-label{font-size:11px;color:#888;text-transform:uppercase;letter-spacing:1px;margin-bottom:5px}.detail-value{font-size:16px;color:#333;font-weight:600}.certificate-id{font-family:monospace;font-size:12px;color:#888;margin-top:30px}.signatures{display:flex;justify-content:space-around;margin-top:50px;padding-top:30px}.signature-block{text-align:center;width:200px}.signature-line{border-top:2px solid #1a237e;margin-bottom:10px}.signature-title{font-size:12px;color:#666;text-transform:uppercase;letter-spacing:1px}.print-btn{display:block;width:200px;margin:30px auto;padding:15px 30px;background:#1a237e;color:white;border:none;border-radius:5px;font-size:16px;cursor:pointer}.print-btn:hover{background:#283593}@media print{body{background:white;padding:0}.certificate-container{box-shadow:none}.print-btn{display:none}}</style></head><body><div class="certificate-container"><div class="certificate-border"></div><div class="certificate-border-inner"></div><div class="certificate-content"><img src="' + logoUrl + '" alt="Company Logo" class="logo"><h1 class="certificate-title">CERTIFICATE</h1><p class="certificate-subtitle">of Achievement</p><p class="presented-to">This is to certify that</p><h2 class="recipient-name">' + certData.employeeName + '</h2><p class="certificate-text">has successfully completed the training program and demonstrated proficiency in <strong>' + certData.application + '</strong>. This certification acknowledges their dedication to professional development and commitment to excellence.</p><div class="details-grid"><div class="detail-item"><div class="detail-label">Email</div><div class="detail-value">' + certData.email + '</div></div><div class="detail-item"><div class="detail-label">Batch Number</div><div class="detail-value">' + certData.batchNumber + '</div></div><div class="detail-item"><div class="detail-label">Date of Issue</div><div class="detail-value">' + certData.issueDate + '</div></div><div class="detail-item"><div class="detail-label">Valid Until</div><div class="detail-value">' + certData.expiryDate + '</div></div></div><div class="signatures"><div class="signature-block"><div class="signature-line"></div><div class="signature-title">Training Manager</div></div><div class="signature-block"><div class="signature-line"></div><div class="signature-title">Program Director</div></div></div><p class="certificate-id">Certificate ID: ' + certData.certificateId + '</p></div></div><button class="print-btn" onclick="window.print()">Print / Save as PDF</button></body></html>';
    return { success: true, htmlContent: html };
  } catch (error) { console.error('Error generating certificate HTML:', error); return { success: false, message: 'Failed to generate certificate: ' + error.message }; }
}

function getEvaluationReportHTML(resultId) {
  try {
    const ss = getSpreadsheet();
    const resultsSheet = ss.getSheetByName('Quiz_Results');
    if (!resultsSheet || resultsSheet.getLastRow() < 2) return { success: false, message: 'Result not found' };
    const resultsData = resultsSheet.getRange(2, 1, resultsSheet.getLastRow() - 1, 10).getValues();
    let resultData = null;
    for (let i = 0; i < resultsData.length; i++) {
      if (resultsData[i][0] === resultId) {
        resultData = { resultId: resultsData[i][0], traineeEmail: resultsData[i][1], traineeName: resultsData[i][2], application: resultsData[i][3], testNumber: resultsData[i][4], correctCount: resultsData[i][5], totalQuestions: resultsData[i][6], scorePercent: resultsData[i][7], timeTaken: resultsData[i][8], submittedDate: resultsData[i][9] };
        break;
      }
    }
    if (!resultData) return { success: false, message: 'Result not found' };
    const passed = resultData.scorePercent >= 70;
    const logoUrl = 'https://learninganddevelopment.net/ANR/Logo/1.png';
    const html = '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Evaluation Report - ' + resultData.traineeName + '</title></head><body><h1>Evaluation Report</h1><p>Trainee: ' + resultData.traineeName + '</p><p>Score: ' + resultData.scorePercent + '%</p><p>Status: ' + (passed ? 'PASSED' : 'FAILED') + '</p><button onclick="window.print()">Print</button></body></html>';
    return { success: true, htmlContent: html };
  } catch (error) { console.error('Error generating evaluation report HTML:', error); return { success: false, message: 'Failed to generate report: ' + error.message }; }
}

function getReportsAndCertificationDataWithCerts(filters, userEmail, userType) {
  const reportsData = getReportsAndCertificationData(filters);
  const certifications = getAllCertifications(userEmail, userType);
  reportsData.tiles = reportsData.tiles || {};
  reportsData.tiles.totalCertifications = certifications.length;
  reportsData.certifications = certifications;
  return reportsData;
}

// ==================== CATEGORY DASHBOARD DATA ====================

function getCategoryDashboardData(categoryName) {
  try {
    const ss = getSpreadsheet();
    const defaultCategories = ['ilt', 'sbl', 'isms', 'misc'];
    const isDefaultCategory = defaultCategories.includes(categoryName.toLowerCase());
    const sheetName = isDefaultCategory ? 'ILT' : categoryName;
    const sheet = ss.getSheetByName(sheetName);

    if (!sheet || sheet.getLastRow() < 2) {
      return { totalTrainings: 0, totalTrainees: 0, upcomingTrainings: 0, recentTrainings: [] };
    }

    const data = sheet.getRange(2, 1, sheet.getLastRow() - 1, 9).getValues();
    const today = new Date();
    const uniqueTrainings = new Set();
    const uniqueTrainees = new Set();
    let upcomingCount = 0;
    const recentTrainings = [];

    data.forEach(row => {
      if (!row[0]) return;
      const rowCategory = String(row[1]).trim().toLowerCase();
      if (isDefaultCategory && rowCategory !== categoryName.toLowerCase()) return;

      uniqueTrainings.add(row[0] + '|' + row[2]);
      uniqueTrainees.add(row[4]);
      const startDate = new Date(row[6]);
      if (startDate > today) upcomingCount++;
    });

    const seenTrainings = new Set();
    for (let i = data.length - 1; i >= 0 && recentTrainings.length < 10; i--) {
      if (!data[i][0]) continue;
      const rowCategory = String(data[i][1]).trim().toLowerCase();
      if (isDefaultCategory && rowCategory !== categoryName.toLowerCase()) continue;

      const key = data[i][0] + '|' + data[i][2];
      if (!seenTrainings.has(key)) {
        seenTrainings.add(key);
        const startDate = new Date(data[i][6]);
        const status = startDate > today ? 'Scheduled' : (new Date(data[i][7]) < today ? 'Completed' : 'In Progress');
        recentTrainings.push({
          batch: data[i][0],
          application: data[i][2],
          startDate: Utilities.formatDate(new Date(data[i][6]), Session.getScriptTimeZone(), 'yyyy-MM-dd'),
          endDate: Utilities.formatDate(new Date(data[i][7]), Session.getScriptTimeZone(), 'yyyy-MM-dd'),
          status: status
        });
      }
    }

    return { totalTrainings: uniqueTrainings.size, totalTrainees: uniqueTrainees.size, upcomingTrainings: upcomingCount, recentTrainings: recentTrainings };
  } catch (error) {
    console.error('Error getting category dashboard data:', error);
    return { totalTrainings: 0, totalTrainees: 0, upcomingTrainings: 0, recentTrainings: [] };
  }
}

// ==================== COMPLIANCE DASHBOARD DATA ====================

function getComplianceDashboardData() {
  try {
    const ss = getSpreadsheet();
    const eventsSheet = ss.getSheetByName('Compliance_Events');
    const statusSheet = ss.getSheetByName('Compliance_Status');

    let totalEvents = 0, upcomingEvents = 0, avgCompliance = 0;
    const today = new Date();

    if (eventsSheet && eventsSheet.getLastRow() > 1) {
      const eventsData = eventsSheet.getRange(2, 1, eventsSheet.getLastRow() - 1, 7).getValues();
      totalEvents = eventsData.length;
      eventsData.forEach(row => {
        if (row[4] && new Date(row[4]) > today) upcomingEvents++;
      });
    }

    if (statusSheet && statusSheet.getLastRow() > 1) {
      const statusData = statusSheet.getRange(2, 5, statusSheet.getLastRow() - 1, 1).getValues();
      let totalComp = 0;
      statusData.forEach(row => { totalComp += Number(row[0]) || 0; });
      avgCompliance = statusData.length > 0 ? Math.round(totalComp / statusData.length) : 0;
    }

    return { totalEvents: totalEvents, upcomingEvents: upcomingEvents, avgCompliance: avgCompliance };
  } catch (error) {
    console.error('Error getting compliance dashboard data:', error);
    return { totalEvents: 0, upcomingEvents: 0, avgCompliance: 0 };
  }
}
